import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter'
import { CssBaseline } from '@mui/material'

import { ThemeProvider } from '@mui/material/styles'
import theme from './theme'

import type { Metadata } from "next"
import Blog from './blog/Blog'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AppRouterCacheProvider>
      <ThemeProvider theme={theme}>
        <CssBaseline />
        <html lang="en">
          <body suppressHydrationWarning>
            <Blog>
              {children}
            </Blog>
          </body>
        </html>
      </ThemeProvider>
    </AppRouterCacheProvider>
  )
}
